export const COVID_DATA_SUCCESS = 'COVID_DATA_SUCCESS';
export const COVID_DATA_PENDING = 'COVID_DATA_PENDING';
export const COVID_DATA_ERROR = 'COVID_DATA_ERROR';

export const COVID_TIME_SERIES_DATA_SUCCESS = 'COVID_TIME_SERIES_DATA_SUCCESS';
export const COVID_TIME_SERIES_DATA_PENDING = 'COVID_TIME_SERIES_DATA_PENDING';
export const COVID_TIME_SERIES_DATA_ERROR = 'COVID_TIME_SERIES_DATA_ERROR';